### ISSUE TITLE
Automatic link refactoring

### ISSUE THREAD

**Issue by Fulachs** [p-fruck/Jimmi#10]
## Summary
Allow users to paste a full link into the "instance" field and automatically fill the room name using the inputed url.

User inputs "https://meet.jit.si/MaximumDocumentationsWinWhen"  into "instance"
-> automatically fill room name: "MaximumDocumentationsWinWhen"

## Motivation
Improves the usability for users

**Comment by p-fruck** [comment]
Hi, thank you for using our project! This is a great idea I'm looking forward to implement, but unfortunately I don't have much time to do so currently, which means you would have to wait a while. If you want to accelerate the process and have the required time and knowledge, feel free to create a PR :)
