### ISSUE TITLE
Give moderator to first person who joins

### ISSUE THREAD

**Issue by Latrolage** [p-fruck/Jimmi#8]
If the bot is the only user on the call, it should give moderator to the first person who joins.

**Comment by p-fruck** [comment]
Welcome to the new project! It took a while, but I guess the plugin will be implemented within the next one or two weeks :smiley:

**Comment by p-fruck** [comment]
The underlying changes have been implemented, the only thing holding me back to implement the changes is my weak understanding of the jitsi-low-level api, see [here](https://github.com/jitsi/lib-jitsi-meet/issues/1800)

**Comment by p-fruck** [comment]
The new capability should now be included on [jimmi.xyz](https://jimmi.xyz). Feel free to open another issues if questions remain :wink:
